name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to create'
        required: true
        default: 'v0.0.0'

jobs:

  build:
    name: Build & Test
    runs-on: ubuntu-latest

    steps:
      # TODO: when 1.17 will be available
      # - name: Set up Go 1.x
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: ^1.17

      # https://github.com/actions/setup-go/issues/21
    - name: Install Go
      run: |
          git clone --depth=1 https://go.googlesource.com/go $HOME/gotip
          cd $HOME/gotip/src
          ./make.bash
          sudo ln -s $HOME/gotip/bin/* /usr/local/bin/
          go version

    - name: Check out code
      uses: actions/checkout@v2

    - name: Build
      run: go build -v -gcflags=-G=3 ./...

    - name: Upload Coverage
      uses: codecov/codecov-action@v1
      continue-on-error: true
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: ./coverage.txt
        fail_ci_if_error: false

  release:
    if: github.event_name == 'workflow_dispatch'

    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout with tags
        run: git fetch --prune --unshallow --tags

      - name: Create release
        run: |
          git log --format="%C(auto) %H %s" `git tag --sort=-committerdate | head -1`...HEAD > changelog.txt
          echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token
          gh release create ${{ github.event.inputs.tag }} -F changelog.txt
